# Generated by Django 3.2 on 2021-04-29 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Thing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Name')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('CNT', 'Continued'), ('RMV', 'Removed')], default='NEW', max_length=3, verbose_name='Status')),
            ],
        ),
    ]
