# Generated by Django 3.2 on 2021-04-29 20:55

from django.db import migrations, models
import django.db.models.deletion


def create_statuses(apps, schema_editor):
    Status = apps.get_model("migration", "Status")
    Status.objects.create(name="New")
    Status.objects.create(name="Continued")
    Status.objects.create(name="Removed")


def update_thing_statuses(apps, schema_editor):
    Thing = apps.get_model("migration", "Thing")
    Status = apps.get_model("migration", "Status")
    for thing in Thing.objects.all():
        thing.new_status = Status.objects.get(name=thing.status)
        thing.save()


class Migration(migrations.Migration):

    dependencies = [
        ("migration", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Status",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=32, verbose_name="Name")),
            ],
        ),
        migrations.AddField(
            model_name="thing",
            name="new_status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="things",
                to="migration.status",
                null=True,
                blank=True,
            ),
        ),
        migrations.RunPython(create_statuses),
        migrations.RunPython(update_thing_statuses),
        migrations.RemoveField(model_name="thing", name="status"),
        migrations.RenameField(
            model_name="thing", old_name="new_status", new_name="status"
        ),
        migrations.AlterField(
            model_name="thing",
            name="status",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="things",
                to="migration.status",
                null=False,
                blank=False,
            ),
        ),
    ]
