# Generated by Django 3.2 on 2021-04-28 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('import_text_choice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='territory',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('CNT', 'Continued'), ('RMV', 'Removed')], default='NEW', max_length=3, verbose_name='Status'),
        ),
    ]
