# Generated by Django 3.2 on 2021-04-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('limit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='eng',
            field=models.ManyToManyField(limit_choices_to={'role__name': 'Engineer'}, related_name='eng_on', to='limit.Person', verbose_name='Engineer'),
        ),
        migrations.AlterField(
            model_name='team',
            name='rep',
            field=models.ManyToManyField(limit_choices_to={'role__name': 'Sales Rep'}, related_name='rep_on', to='limit.Person', verbose_name='Sales Rep'),
        ),
    ]
